version: 2.1

executors:
  python38-executor:
    docker:
      - image: circleci/python:3.8.2-buster
  python37-executor:
    docker:
      - image: circleci/python:3.7.7-buster

jobs:
  setup-environment:
    parameters:
      e:
        type: executor
      n:
        type: string
    executor: << parameters.e >>
    steps:
      - checkout
      - run:
          name: Version information
          command: python --version
      - run:
          name: << parameters.e >> Setup VENV & install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade "pip>=19.3"
            pip install -e . --no-cache-dir
      - persist_to_workspace:
          root: ~/
          paths: project/*  
  setup-environment37:
    executor: python37-executor
    steps:
      - checkout
      - run:
          name: Version information
          command: python --version
      - run:
          name: 3.7 Setup VENV & install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade "pip>=19.3"
            pip install -e . --no-cache-dir
      - persist_to_workspace:
          root: ~/
          paths: project/*
  unit-tests:
    parameters:
      e:
        type: executor
      n:
        type: string
    executor: << parameters.e >>
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: << parameters.e >> Unit tests
          command: |
            source venv/bin/activate
            make test
  linting:
    parameters:
      e:
        type: executor
      n:
        type: string
    executor: << parameters.e >>
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: << parameters.e >> Python code style checking
          command: |
            source venv/bin/activate
            make lint
  type-checking:
    parameters:
      e:
        type: executor
      n:
        type: string
    executor: << parameters.e >>
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: << parameters.e >> Type checking
          command: |
            source venv/bin/activate
            make type
  code-coverage:
    parameters:
      e:
        type: executor
      n:
        type: string
    executor: << parameters.e >>
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: << parameters.e >> Coverage checking
          command: |
            source venv/bin/activate
            make coverage
      - run:
          name: Upload coverage
          command: |
            source venv/bin/activate
            pip install codecov
            codecov
  publish-docs:
      executor: python38-executor
      steps:
        - attach_workspace:
            at: ~/
        - run:
            name: install aws cli
            command: |
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
        - run:
            name: Build and release docs
            command: |
              source venv/bin/activate
              cd docs
              make publish-docs

workflows:
  main:
    jobs:
      - setup-environment:
          e: python38-executor
          n: "3.8"
      - type-checking:
          e: python38-executor
          n: "3.8"
          requires:
            - setup-environment
      - linting:
          e: python38-executor
          n: "3.8"
          requires:
            - setup-environment
      - unit-tests:
          e: python38-executor
          n: "3.8"
          requires:
            - setup-environment
      - code-coverage:
          e: python38-executor
          n: "3.8"
          requires:
            - setup-environment
      - setup-environment:
          e: python37-executor
          n: "3.7"
      - type-checking:
          e: python37-executor
          n: "3.7"
          requires:
            - setup-environment37
      - linting:
          e: python37-executor
          n: "3.7"
          requires:
            - setup-environment37
      - unit-tests:
          e: python37-executor
          n: "3.7"
          requires:
            - setup-environment37
      - code-coverage:
          e: python37-executor
          n: "3.7"
          requires:
            - setup-environment37

  update-docs:
    jobs:
      - approve-update:
          type: approval
          filters:
            branches:
              only:
                - master
      - setup-environment:
          requires:
            - approve-update
      - publish-docs:
          context: aws
          requires:
            - setup-environment
